# Netlify configuration (Sep 2025)
# React SPA with build step

[build]
  command = "npm ci && npm run build"
  publish = "dist-react"

# =====================================================
# CLEAN URLs - SEO OPTIMIZED (2025 BEST PRACTICES)
# =====================================================

# Force redirect ALL .html extensions to clean URLs
[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 301
  force = true

# Specific clean URL mappings and optimized redirects
[[redirects]]
  from = "/success"
  to = "/dashboard"
  status = 301

[[redirects]]
  from = "/preferences"
  to = "/dashboard?tab=preferences"
  status = 301

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

# SPA routing - catch all routes and serve index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
