# Netlify configuration (Sep 2025)
# Static site, no build step needed. Enables form detection at deploy time.

[build]
  command = ""
  publish = "."

# =====================================================
# CLEAN URLs - SEO OPTIMIZED (2025 BEST PRACTICES)
# =====================================================

# Force redirect ALL .html extensions to clean URLs
[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 301
  force = true

# Specific clean URL mappings and optimized redirects
[[redirects]]
  from = "/success"
  to = "/dashboard"
  status = 301

[[redirects]]
  from = "/preferences"
  to = "/dashboard?tab=preferences"
  status = 301

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/unsubscribe"
  to = "/unsubscribe.html"
  status = 200

# Izipay payment routes - Corregido Sept 2025
[[redirects]]
  from = "/payment/success"
  to = "/payment-success.html"
  status = 200

[[redirects]]
  from = "/payment/failed"
  to = "/payment-failed.html"
  status = 200

# Single webhook endpoint (elimina duplicación)
[[redirects]]
  from = "/payment/callback/test"
  to = "/.netlify/functions/webhook_handler"
  status = 200

[[redirects]]
  from = "/payment/callback/production"
  to = "/.netlify/functions/webhook_handler"
  status = 200

[[redirects]]
  from = "/webhook/izipay_webhook"
  to = "/.netlify/functions/webhook_handler"
  status = 200
